version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/hello_world
  # BeforeInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root
   ApplicationStart:
     - location: /var/www/hello_world/bin/start.sh
       timeout: 300
       runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
