# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo Install postgres
      - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - apt-get update -y
      - apt-get install -y postgresql-11
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - echo Initializing postgres
      - pg_ctlcluster 11 main start
      - echo Preparing database to run tests...
      - RAILS_ENV=test bundle exec rails db:setup
      - RAILS_ENV=test bundle exec rails db:migrate
  build:
    commands:
      - echo Running tests...
      - bundle exec rspec
